### ISSUE TITLE
some simple questions...

### ISSUE THREAD

**Issue by PAOK1926** [alfg/docker-nginx-rtmp#108]
i finally managed to setup and stream..
thank you for the great piece of software..
I tried to setup something like this, 3-4 times the last month, without success..
but with this i was streaming almost instantly..
and two questions:
1. when the player starts is muted. is there a remedy with this ?
2. the button for full screen is grayed.. why ?

**Comment by alfg** [comment]
Hey @PAOK1926, 

Glad you like the Docker image. 

> 1. when the player starts is muted. is there a remedy with this ?
The example player I use has mute enabled by default. Since this is based on the player configuration, you can disable it if you need to by removing the `muted` attribute.

https://github.com/alfg/docker-nginx-rtmp/blob/master/static/player.html#L32

> 2. the button for full screen is grayed.. why ?
I tried running the example again, but I don't see the full screen option grayed out. I am able to fullscreen.

**Comment by alfg** [comment]
Closing. Feel free to respond if you have any other questions. Thanks!
