### ISSUE TITLE
How do I modify nginx.conf?

### ISSUE THREAD

**Issue by dracenliu** [alfg/docker-nginx-rtmp#32]

**Comment by alfg** [comment]
Hi @dracenliu,

You can either fork and modify the `nginx.conf` on your fork, or mount a volume to overwrite the `nginx.conf`.

**Comment by dracenliu** [comment]
I'm run with this cmd ,but it doesn't work with my config!What should I do?
```
docker run -it -p 1937:1935 -p 8088:80 -v /root/nginx.conf:/etc/nginx/nginx.conf:ro --rm alfg/nginx-rtmp
```

**Comment by mikeydiamonds** [comment]
@dracenliu just in case you still needed assistance with customizing nginx.conf, you can just mount a volume:
docker run -it -p 1935:1935 -p 8080:80 -v /host/path/to/nginx.conf.template:/etc/nginx/nginx.conf.template --rm alfg/nginx-rtmp

Due to https://github.com/alfg/docker-nginx-rtmp/pull/50 you have to mount over `nginx.conf.template`
