### ISSUE TITLE
Alpine 3.3 reached EoL

### ISSUE THREAD

**Issue by RobertLowe** [alfg/docker-nginx-rtmp#5]
Alpine 3.3 reached EoL a few months ago - https://en.wikipedia.org/wiki/Alpine_Linux#Version_history

nginx & rtmp module have had patches and ffmpeg has had a minor bump.

I don't expect any action this is purely for note/heads up. Thanks for the great docker repo, out of the handful I've dug into this one is top dollar. 👍

**Comment by alfg** [comment]
Ah, thanks for the heads up and the kind words! I'll look into updating this soon!

**Comment by alfg** [comment]
So I tried updating to the latest Alpine 3.7, but FFmpeg doesn't seem to build with the `--enable-openssl` flag. It's probably due to Alpine switching to `libressl`. It's similar to the issue reported here:
https://trac.ffmpeg.org/ticket/6580

So I can update Alpine to 3.4 (which still seems to be supported for a bit longer with openssl) and update to Alpine 3.7 once FFmpeg supports building with the `--enable-libtls` option.

Another option is to remove the `--enable-openssl` build flag. I'm not too sure on the scope on how this is used along with nginx-rtmp though.

Anyway, I'm updating this image to Alpine 3.4 soon, along with the version bumps from ffmpeg and nginx-vod-module. I'll add another ticket for Alpine 3.7.
