### ISSUE TITLE
mime.types not found

### ISSUE THREAD

**Issue by unjust** [alfg/docker-nginx-rtmp#61]
I am using the image to create an instance on Google cloud.
I'm using my own nginx.conf that I used successfully with a previous nginx rtmp docker container, which used `buildpack-deps:stretch` not Alpine.

When I start up this container, when it gets to where I include `mime.types` in the config I get an error that its not found, 

`nginx: [emerg] open() "/etc/nginx/mime.types" failed (2: No such file or directory) `

and I don't see it in the container in `/etc/nginx`

Is something missing from the configuration? Do I need to add my own? Thanks.

Part of my nginx.conf:
```#user  nobody;	
worker_processes  1;	

#error_log  logs/error.log;	
#error_log  logs/error.log  notice;	
#error_log  logs/error.log  info;	

#pid        logs/nginx.pid;	


events {	
    worker_connections  1024;	
}	


http {	
    include       mime.types;	
    default_type  application/octet-stream;
...
```

**Comment by alfg** [comment]
Ah, it's because in the release image, I don't copy over the base nginx config files, but only the `nginx.conf.template` file.

I just added a fix to this on:
https://github.com/alfg/docker-nginx-rtmp/commit/772e4deeb02df1b0ddc2220e9c7005eea28fa995

It's building now. Try the latest image and try again, please.

**Comment by unjust** [comment]
I see. I was thinking it might be something like that.
I'm new to all this :) Thank you I'll give it a whirl.

**Comment by unjust** [comment]
I'm running into some issues when trying to use my own nginx.conf and not the one in your repo.

If I put my own nginx.conf in the directory of my Dockerfile, which is based off of yours
- the container spins up but when I attach to it with bin/sh the command line is messed up.

is this because docker is confused between my nginx.conf and the one that ships with the image that the container doesnt seem right?

or does my nginx.conf have to have env vars to be replaced like yours or envsubst will error or something?

**Comment by alfg** [comment]
When the container starts, it runs `envsubst` to copy the nginx.template file to nginx.conf. The only way to restart nginx without exiting the container is to re-run the CMD in the shell. `daemon` mode in nginx is disabled since this is running in a container and needs an entrypoint.

When it didn't work before, did you capture any errors in the output?

**Comment by unjust** [comment]
Ok it may have been that I didnt specify `daemon mode` to off in the conf file.
I wasnt able to see any errors that informed me as to what was going on. 

Thanks!

**Comment by alfg** [comment]
Ok, thanks for checking into it!
