### ISSUE TITLE
how to change config without restart container

### ISSUE THREAD

**Issue by unluckyBear** [alfg/docker-nginx-rtmp#70]
i have mount my custom nginx.conf,  but when i modify the config file it doesn't work util restart the nginx container.
how to reload without restart?   thank you!

**Comment by alfg** [comment]
Hi @unluckyBear, 

NGINX needs to be restarted (or reloaded) in order to apply new `nginx.conf` changes, therefore the container will need to be restarted as well. 

However, if you are doing this to test configuration changes, you can start the container with `sh` and just run the CMD defined in Dockerfile to start nginx manually. For example:
```
docker-compose run --service-ports nginx-rtmp sh

envsubst "$(env | sed -e 's/=.*//' -e 's/^/\$/g')" < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx
```

This way you can start/stop the nginx process as needed while being able to modify your mounted config.
