### ISSUE TITLE
About the methods of certificate generation for stream server.

### ISSUE THREAD

**Issue by hongyi-zhao** [alfg/docker-nginx-rtmp#85]
I noted some other methods on certificate generation for stream server as shown below:

1. Described in the document of [Node-Media-Server](https://github.com/illuspas/Node-Media-Server#generate-certificate):
```
Generate certificate

openssl genrsa -out privatekey.pem 1024
openssl req -new -key privatekey.pem -out certrequest.csr 
openssl x509 -req -in certrequest.csr -signkey privatekey.pem -out certificate.pem
```
2. Stated in document of [rtmp-server](https://github.com/jjlakis/rtmp-server#how-to-use):

```
 Generate TLS certificates for your HTTP domains:

$ docker-compose run --rm --service-ports certbot certonly -d you.yourdomain.com --standalone

Note: certbot runs in stand-alone mode - it binds :80 on your system.
```
Can either of the above methods be used by the docker-nginx-rtmp? If so, what's the differences between these two methods? OTOH, according to my limited understanding on certificate, with method 1, it should only generate a self-signed certificate. I'm not sure if my understanding is correct or not. Any hints will be highly appreciated.

Regards,
HY

**Comment by alfg** [comment]
It depends. It's only self-signed if you are generating the cert yourself (and signing yourself), rather than through a CA provider.

If using Let's Encrypt, you can run the certbot image side-by-side your rtmp container, as long as it places the certs in the mounted directory and the acme challenge can be reached for auto-renewal every 3 months or so.

I would refer to the documentation guide:
https://certbot.eff.org/docs/using.html

**Comment by hongyi-zhao** [comment]
If we are only interested in the encryption aspect of our certificate, not the third party validation of our host’s authenticity, the self-signed certificate should be enough.

**Comment by alfg** [comment]
Should be good enough, but some clients will give a warning or reject a self-signed certificates unless configured to trust. Depends on your use case.
