### ISSUE TITLE
A severe resolution loss when rebroadcasting high definition stream. 

### ISSUE THREAD

**Issue by hongyi-zhao** [alfg/docker-nginx-rtmp#86]
I try to rebroadcast the China's cctv1 high definition channel with the following method:

```
$ docker run -dit -p 1935:1935 -p 4430:443 -p 8000:80 -v ./nginx.conf:/etc/nginx/nginx.conf.template -v ~/Public/repo/www.dnspod.cn/ssl/auto.hyddns.xyz/Nginx:/opt/certs --rm nginx-rtmp
$ ffmpeg -re -i rtmp://58.200.131.2:1935/livetv/cctv1hd -f flv "rtmp://localhost:1935/stream/surveillance"
$ ffplay https://auto.hyddns.xyz/live/surveillance.m3u8
```
I observed a severe resolution loss. See the following screenshot for mor info:

![image](https://user-images.githubusercontent.com/11155854/107173498-dfabf700-6a02-11eb-8cbb-4359e0246138.png)

So, how can I do a lossless rebroadcasting for high definition stream with docker-nginx-rtmp? Any hints will be highly appreciated.

Regards,
HY

**Comment by alfg** [comment]
Hey @hongyi-zhao, 

It's difficult to say since it can be a a variety of factors including hardware resources, network, encoding and caching setup. First things to try would be to experiment with different ffmpeg encoding options and try removing some bitrate variants. FFmpeg is very CPU intensive.

Keep in mind, this project is a template for nginx-rtmp and must be tuned and configured based on your resources setup.
